require 'gedspec/gedcom/extract'
require 'gedspec/gedcom/structure'
require 'gedspec/gedcom/file'

require 'gedspec/file/associations'

require 'gedspec/file'
require 'gedspec/header'
require 'gedspec/individual'
require 'gedspec/family'
require 'gedspec/repository'
require 'gedspec/source'
require 'gedspec/note'
require 'gedspec/media_object'
require 'gedspec/personal_name'
require 'gedspec/reference_number'
